let filmes = [
    {
        nome: "A possessão de deborah logan",
        genero: 1,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Nefarious",
        genero: 1,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Popeye com robin willians",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "All eyez on me",
        genero: 0,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Moonshine and valentine",
        genero: 0,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "O homem dos sonhos",
        genero: 0,
        tipo: 0,
        status: 0,
        stream: 0,
        estrelas: 1,
    },
    {
        nome: "Invasão Zombie",
        genero: 5,
        status: 0,
        stream: 1,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "the gangster, the cop, the evil",
        genero: 0,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 0,
    },
    {
        nome: "Supernatural",
        genero: 5,
        status: 1,
        stream: 2,
        estrelas: 5,
        tipo: 2,
    },
    {
        nome: "Tiras, só que não",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Um pobretão na casa branca",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Em pé de guerra",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Tinha que ser ele?",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "O pacote",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Padrinhos LTDA",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Juntos pelo acaso",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Mulheres ao ataque",
        genero: 2,
        status: 0,
        stream: 0,
        estrelas: 1,
        tipo: 1,
    },
    {
        nome: "Gente grande",
        genero: 2,
        status: 1,
        stream: 0,
        estrelas: 3,
        tipo: 1,
    },
    {
        nome: "O agente faixa-preta",
        genero: 3,
        status: 1,
        stream: 1,
        estrelas: 5,
        tipo: 3,
    },
    {
        nome: "Click",
        genero: 5,
        status: 1,
        stream: 0,
        estrelas: 2,
        tipo: 1,
    },
    {
        nome: "Homem de ferro",
        genero: 5,
        status: 1,
        stream: 4,
        estrelas: 5,
        tipo: 1,
    },
    {
        nome: "O tempo trás você pra mim",
        genero: 4,
        status: 1,
        estrelas: 3,
        stream: 1,
        tipo: 3,
    },
    {
        nome: "Meu demônio favorito",
        genero: 4,
        status: 1,
        estrelas: 3,
        stream: 1,
        tipo: 3,
    },
    {
        nome: "Amor rural",
        genero: 4,
        status: 1,
        estrelas: 3,
        stream: 1,
        tipo: 3,
    },
    {
        nome: "Vinte e cinco, vinte e um",
        genero: 4,
        status: 1,
        estrelas: 5,
        stream: 1,
        tipo: 3,
    },
    {
        nome: "Pretendente surpresa",
        genero: 4,
        status: 1,
        estrelas: 4,
        stream: 1,
        tipo: 3,
    },
    {
        nome: "Spy x family",
        genero: 5,
        status: 1,
        estrelas: 3,
        stream: 6,
        tipo: 5,
    },
    {
        nome: "One punch man",
        genero: 5,
        status: 1,
        estrelas: 3,
        stream: 6,
        tipo: 5,
    },
    {
        nome: "Nanatsu no taizai",
        genero: 4,
        status: 1,
        estrelas: 3,
        stream: 1,
        tipo: 5,
    },
    {
        nome: "The Dreaming Boy",
        genero: 4,
        status: 1,
        estrelas: 4,
        stream: 6,
        tipo: 5,
    },
    {
        nome: "Death note",
        genero: 3,
        status: 1,
        estrelas: 5,
        stream: 1,
        tipo: 5,
    },
    {
        nome: "My Darling in the franxx",
        genero: 5,
        status: 1,
        estrelas: 5,
        stream: 6,
        tipo: 5,
    },
    {
        nome: "Solo leveling",
        genero: 5,
        status: 1,
        estrelas: 5,
        stream: 6,
        tipo: 5,
    },
    {
        nome: "The hidden dungeon only i can enter",
        genero: 5,
        status: 1,
        estrelas: 2,
        stream: 6,
        tipo: 5,
    },
    {
        nome: "Ayla sometimes",
        genero: 3,
        status: 1,
        estrelas: 2,
        stream: 6,
        tipo: 5,
    },
    {
        nome: "The Winchesters",
        genero: 5,
        status: 1,
        estrelas: 2,
        stream: 2,
        tipo: 2,
    },
    {
        nome: "Yellow Jackets",
        genero: 3,
        status: 1,
        estrelas: 1,
        stream: 1,
        tipo: 2,
    },
    {
        nome: "One Piece",
        genero: 2,
        status: 1,
        estrelas: 3,
        stream: 1,
        tipo: 6,
    },
    {
        nome: "Homem de ferro 2",
        genero: 5,
        status: 1,
        estrelas: 5,
        stream: 4,
        tipo: 1,
    },
    {
        nome: "Homem de ferro 3",
        genero: 5,
        status: 1,
        estrelas: 5,
        stream: 4,
        tipo: 1,
    },
    {
        nome: "O espetacular homem aranha",
        genero: 5,
        status: 1,
        estrelas: 5,
        stream: 1,
        tipo: 1,
    },
    {
        nome: "Arcane",
        genero: 5,
        status: 2,
        estrelas: 5,
        stream: 1,
        tipo: 2,
    },
    {
        nome: "Doctor Who",
        genero: 5,
        status: 3,
        estrelas: 5,
        stream: 0,
        tipo: 2,
    },
    {
        nome: "Intocáveis",
        genero: 2,
        status: 0,
        estrelas: 1,
        stream: 0,
        tipo: 1,
    },
    {
        nome: "Um sonho de liberdade",
        genero: 0,
        status: 0,
        estrelas: 0,
        stream: 0,
        tipo: 1,
    },
    {
        nome: "Mesmo se nada der certo",
        genero: 0,
        status: 0,
        estrelas: 1,
        stream: 0,
        tipo: 1,
    },
    {
        nome: "Efeito borboleta",
        genero: 5,
        status: 1,
        estrelas: 5,
        stream: 0,
        tipo: 1,
    },
];
